apiVersion: v1
kind: ReplicationController
metadata:
  name: centos-ssh-rc
spec:
  replicas: 1
  selector:
    app: centos-ssh
  template:
    metadata:
      labels:
        app: centos-ssh
    spec:
      containers:
      - name: centos-ssh
        image: 172.30.251.136:5000/zhaojizhuang/centos-ssh:6
