apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-rc
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: 172.30.251.136:5000/zhaojizhuang/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
