apiVersion: v1
kind: Pod
metadata:
 labels:
   server-id: "2"
   server-type: kafka
 name: pod-kafka-2
spec:
 containers:
  - name: kafka
    env: 
    - name: KAFKA_ADVERTISED_PORT
      value: "9092"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: svr-kafka-2 
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper-1:2181
    image: 172.30.251.136:5000/zhaojizhuang/kafka
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9092
      protocol: TCP

