apiVersion: v1
kind: Service
metadata:
  name: svr-np-spark-master
spec:
  type: NodePort
  selector:      
    server-id: "1"
    server-type: spark
  ports:
   - port: 8080
     protocol: TCP
     nodePort: 30080
