apiVersion: v1
kind: Service
metadata:
  name: svr-np-squid
spec:
  type: NodePort
  selector:      
    server-id: "1"
    server-type: squid
  ports:
   - port: 3128
     protocol: TCP
     nodePort: 30128
